import {useEffect, useState} from "react";

import Head from "next/head";
import dynamic from "next/dynamic";

const CustomComponent = dynamic(
  () => import("../components/custom-component"),
  { ssr: false }
);

const customComponentFromDatabase = [
  {
    id: "remote/Counter",
    props: {
      startCount: 10,
    },
  },
  { id: "remote/Loading" },
];

export default function Home() {
  const [value, setValue] = useState(false);

  const [component, setComponent] = useState<any[]>([]);
  useEffect(() => {
    const timeout = setTimeout(
      () => setComponent(customComponentFromDatabase),
      5000
    );
    return () => clearTimeout(timeout);
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>NEXT-JS HOST</div>
      <section>
        <header>This is the suspense:</header>
        {component.map((component) => (
          <CustomComponent
            key={component.id}
            componentId={component.id}
            componentProps={component.props}
          />
        ))}
      </section>
      <br />
      <section>
        <header>This is a diferent component changing current state</header>
        <button onClick={() => setValue((v) => !v)}>
          Toggle {value ? "on" : "off"}
        </button>
      </section>
    </div>
  );
}
